### ISSUE TITLE
Statistical modeling - Errori nei gradi di libertà

### ISSUE THREAD

**Issue by moiraghif** [moiraghif/appunti#30]
Ragazzi, mi pare di aver trovato degli errori nei gradi di libertà (presenti proprio nella dispensa e quindi penso siano del prof)

Per esempio, Test di White: il prof lo segna con k gdl ma dovrebbero essere k-1 (https://en.wikipedia.org/wiki/White_test)

Adesso faccio una revisione generale ma impiego un po' (e può scappare l'errore anche a me): se notate qualcosa di sbagliato correggete :)

**Comment by faber6911** [comment]
La questione gdl è sempre abbastanza delicata, hai fatto bene a farlo notare, avevo dato per scontato che almeno quelli fossero giusti
